site_name: HollowEngine Wiki

repo_name: HollowHorizon/HollowEngine
repo_url: https://github.com/HollowHorizon/HollowEngine

docs_dir: docs

nav:
  - Введение: index.md
  - Скриптинг: 
    - Введение: scripting/introduction.md
    - Сюжетные события: 
      - scripting/story_events.md
      - НПС:
        - Создание нпс: scripting/story_events/npcs/creation.md

  - Hollow Engine | GUIDE: 
    - hollowengine-guide/introduction.md

    - Начало: 
      - Для работы требуется...: hollowengine-guide/Begin/requeres.md
      - Новые папки: hollowengine-guide/Begin/folders.md
      - Начинаем: hollowengine-guide/Begin/starting.md
      - Типы скриптов: hollowengine-guide/Begin/scripts-type.md
      - Ваши ресурсы: hollowengine-guide/Begin/assets.md

    - SE-KTS: 
      - NPCs: 
        - Спавн NPC: hollowengine-guide/Script-SE/NPCs/spawn-npc.md
        - Действие для NPC: hollowengine-guide/Script-SE/NPCs/actions-npc.md
        - Анимации NPC: hollowengine-guide/Script-SE/NPCs/animations-npc.md
        - Доп. настройки NPC: hollowengine-guide/Script-SE/NPCs/npc-configure.md
        - Задачи для NPC: hollowengine-guide/Script-SE/NPCs/npc-quest.md
        - Убрать NPC: hollowengine-guide/Script-SE/NPCs/npc-remove.md

      - Диалоговая система: 
        - Диалог: hollowengine-guide/Script-SE/Dialogues/dialogue.md
        - хз как назвать: hollowengine-guide/Script-SE/Dialogues/send-message.md

      - Касцены: 
        - Камера: hollowengine-guide/Script-SE/Cutscenes/camera.md
        - Fade In/Out: hollowengine-guide/Script-SE/Cutscenes/fadeInOut-effect.md

      - Дополнительно: 
        - Таймер ожидания: hollowengine-guide/Script-SE/Tools/wait.md
        - Отобрадение в руке у NPC: hollowengine-guide/Script-SE/Tools/ItemHandVisible.md
        - Стандартые анимации NPC: hollowengine-guide/Script-SE/Tools/standartAnimationType.md
        - Интерполяции: hollowengine-guide/Script-SE/Tools/interpolations.md

      - Прочее: 
        - Менеджер ивентов: hollowengine-guide/Others/event-manager.md
        - Новое измерение: hollowengine-guide/Others/special-dimension.md

      - Дибильные туториалы: 
        - Туториал-1: hollowengine-guide/Tutorials/tutorial-1.md
        - Туториал-2: hollowengine-guide/Tutorials/tutorial-2.md
        - Туториал-3: hollowengine-guide/Tutorials/tutorial-3.md

    - MOD-KTS:
      - Ищем информацию: hollowengine-guide/Script-MOD/search-information.md
      - Новый предмет: hollowengine-guide/Script-MOD/add-newItem.md
      - Запуск скрипта, при первом заходе в мир: hollowengine-guide/Script-MOD/start-script-enter-to-game.md

    - CONTENT-KTS:
      - Крафты:
        - Верстак: hollowengine-guide/Script-CONTENT/recipes/craftingTable-recipe.md
        - Печь: hollowengine-guide/Script-CONTENT/recipes/furnace-recipe.md
        - Плавильня: hollowengine-guide/Script-CONTENT/recipes/blastFurnace-recipe.md
        - Коптильня: hollowengine-guide/Script-CONTENT/recipes/smoker-recipe.md
        - Костёр: hollowengine-guide/Script-CONTENT/recipes/campFire-recipe.md
      - Ищем информацию: hollowengine-guide/Script-CONTENT/search-information.md

theme:
  name: material
  palette:
    - scheme: slate
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode



  features:
    - content.code.annotate
    - content.code.copy
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.integrate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - tables
  - toc

extra_css:
  - stylesheets/extra.css