site_name: HollowEngine Wiki

repo_name: HollowHorizon/HollowEngine
repo_url: https://github.com/HollowHorizon/HollowEngine

docs_dir: docs

nav:
  - Введение:
      - index.md
      - Установка: install.md
  - Скриптинг:
      - Введение: scripting/introduction.md
      - Сюжетные события:
          - scripting/story_events.md
          - Действия:
              - Таймеры и ожидания: scripting/story_events/actions/waiters.md
              - Условия и ветвления: scripting/story_events/actions/conditions.md
              - Циклы: scripting/story_events/actions/loops.md
              - Асинхронные события: scripting/story_events/actions/async.md
          - Персонажи:
              - Создание персонажа: scripting/story_events/npcs/creation.md
              - Настройка персонажа: scripting/story_events/npcs/settings.md
              - Настройка модели персонажа: scripting/story_events/npcs/model_features.md
              - Перемещение и направление взгляда персонажа: scripting/story_events/npcs/moving.md
              - Возможности персонажей: scripting/story_events/npcs/capabilities.md
              - Анимирование персонажей: scripting/story_events/npcs/animations.md
          - Игроки:
              - Изменение моделей: scripting/story_events/players/configure.md
              - Анимации игроков: scripting/story_events/players/animations.md
          - Мир:
              - Время: scripting/story_events/world/time.md
          - Окно диалога:
              - Базовые возможности: scripting/story_events/dialogues/features.md
          - Катсцены:
              - Камера: scripting/story_events/cutscenes/camera.md
              - Переходы: scripting/story_events/cutscenes/transitions.md
          - Список Событий:
              - scripting/story_events/event_list/event_list.md
          - Эффекты:
              - Частицы: scripting/story_events/effects/particles.md
      - Общее:
          - Разное:
              - Интерполяции: scripting/common/util/interpolations.md
          - Импорт скриптов: scripting/common/imports.md
  - Возможности:
      - Загрузчик ресурсов: features/resources.md
      - Измерение рассказчика: features/dimension.md

theme:
  name: material
  palette:
    - scheme: slate
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode



  features:
    - content.code.annotate
    - content.code.copy
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.integrate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - tables
  - toc

extra_css:
  - stylesheets/extra.css